---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaNodePool
metadata:
  name: dual-nodepool
  namespace: event-collector
  labels:
    strimzi.io/cluster: event-cluster
spec:
  replicas: 3
  roles:
    - controller
    - broker
  storage:
    type: ephemeral # 테스트 목적으로 임시 스토리지 사용
  resources:
    requests:
      cpu: "500m"
      memory: "1Gi"
    limits:
      cpu: "500m"
      memory: "1Gi"

---
apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: event-cluster
  namespace: event-collector
  annotations:
    strimzi.io/node-pools: enabled
    strimzi.io/kraft: enabled
spec:
  kafka:
    version: 4.1.0
    replicas: 3
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false # 테스트 목적으로 false 설정
      - name: external
        port: 9094
        type: nodeport
        tls: false
        configuration:
          bootstrap:
            nodePort: 30092       # 클러스터 전체 진입용 NodePort
          brokers:
            - broker: 0
              nodePort: 30093     # broker-0 NodePort
            - broker: 1
              nodePort: 30094     # broker-1 NodePort
            - broker: 2
              nodePort: 30095     # broker-2 NodePort
    config:
      process.roles: "controller,broker" # 컨트롤러 및 브로커 역할 설정
      offsets.topic.replication.factor: 3 # 오프셋 토픽 복제 개수
      transaction.state.log.replication.factor: 3 # 트랜잭션 로그 복제 개수
      transaction.state.log.min.isr: 2 # 트랜잭션 로그 최소 ISR 개수
      default.replication.factor: 3 # 기본 토픽 복제 개수
      min.insync.replicas: 2 # ISR 최소 개수
    storage:
      type: ephemeral # 테스트 목적으로 ephemeral 설정
  entityOperator:
    topicOperator: {}
    userOperator: {}